name: Cache
on: push
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          key: cache-key
          path: dummy

      - run: |
          if [ -f dummy ]; then
            echo "✅ cache Yes"
          else
            echo "❌ cache No"
            sleep 20
            touch dummy
          fi
          